blog/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls',namespace='blog')),
    path('job/', include('job_app.urls',namespace='job'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from . import views
app_name = 'blog_app'
urlpatterns=[
    path('',views.all_blogs,name='all_blogs'),
    path('<int:id>',views.blog_detail,name='blog_detail'),
]

job_app/urls.py
from django.urls import path
from . import views
app_name = 'job_app'

urlpatterns=[
    path('',views.home,name='home'),
]

blog_app/models.py
from django.db import models
import datetime
from django.utils.text import slugify
# Create your models here.
class Blog(models.Model):
    title = models.CharField(blank=True, max_length=100)
    slug = models.SlugField(blank=True,null=True)
    pub_date = models.DateTimeField(blank=True, default=datetime.datetime.now)
    body = models.TextField(blank=True)
    image = models.ImageField(upload_to="blog_images/")

    def save(self, *args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args,**kwargs)
        
    def __str__(self):
        return self.title

job_app/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    summary = models.CharField(max_length=100)
    image = models.ImageField(upload_to="blog_images/")


    def __str__(self):
        return self.summary

blog_app/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    all_blogs = Blog.objects.all()
    return render(request,'blog_app/all_blogs.html',{
        'all_blogs':all_blogs,
    })

def blog_detail(request,id):
    blog = get_object_or_404(Blog,pk=id)

    return render(request,'blog_app/blog.html',{
        'blog':blog,
    })

job_app/views.py
from django.shortcuts import render
from .models import Job
# Create your views here.
def home(request):
    jobs = Job.objects.all()
    return render(request,'job_app/home.html',{
        'jobs':jobs
    })

blog_app/templates/blog_app/all_blogs.html
{% extends "base.html" %}

{% block content%}

<main>
<div class="container">
  <h1 class="text-center pt-4">Welcome to Mohamed's Blog</h1>
  <br>
  <br>
  <h2>Latest Posts</h2>
  <hr>
  {% for blog in all_blogs %}
    <a href="{% url 'blog:blog_detail' blog.pk %}">
      <h3>{{blog.title}}</h3>
    </a>
    {{blog.pub_date|date:"F j, Y"}}
    <br>
    <br>
    <img src="{{blog.image.url}}" class="img-fluid" height=200 width=200>
    <br>
    <p>{{blog.body|truncatechars:50 }}</p>
  {% endfor %}
</div>
  

</main>

{% endblock %}

blog_app/templates/blog_app/blog.html
{% extends "base.html" %}

{% block content%}
    
<main>
<div class="container">
  <h1 class="text-center pt-4">Welcome to Mohamed's Blog</h1>
  <br>
  <br>
  <h2>My Posts</h2>
  <hr>

    <h3>{{blog.title}}</h3>

    {{blog.pub_date|date:"F j, Y"}}
    <br>
    <br>
    <img src="{{blog.image.url}}" class="img-fluid" height=200 width=200>
    <br>
    <p>{{blog.body|truncatechars:50 }}</p>
  
</div>
  

</main>

{% endblock %}

job_app/templates/job_app/home.html
{% extends "base.html" %}

{% block content%}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Hi, I'm Mohamed</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Email Me</a>
          
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for job in jobs %}
          
        
        <div class="col">
          <div class="card shadow-sm">
            <img class="card-img-top" src="{{job.image.url}}"/>
            <div class="card-body">
              <p class="card-text">{{job.summary}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.87.0">
    <title>Album example · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>

    

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'job:home'%}">Welcome </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav" >
      <div class="navbar-nav ml-auto" style="margin-left: auto !important;">
          <a class="nav-item nav-link"href="https://twitter.com/MohamedElrfaay4">Twitter</a>
          <a class="nav-item nav-link" href="#">Resume</a>  
          <a class="nav-item nav-link" href="{% url 'blog:all_blogs'%}">Blog</a>
             
      </div>
    </div>
  </div>
</nav>

</header>
{% block content %}{% endblock content %}

<footer class="text-muted py-5">
  <div class="container text-center">
    <p>&copy; Mohamed Elrfaay {% now "Y"%}</p>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

      
  </body>
</html>